import { MockEmployee } from '../mockDataService';

export const additionalEmployees: MockEmployee[] = [
  {
    id: 'emp007',
    name: 'Dr. Youcef Hamidi',
    email: 'y.hamidi@fsecsg.dz',
    type: 'enseignant',
    grade: 'Maitre de Conférences B',
    currentEchelon: 6,
    appointmentDate: new Date('2017-02-20'),
    lastEvaluationScore: 16.8,
    status: 'active',
    department: 'Économie',
    salary: 92000,
    phoneNumber: '+213 555 789 012',
    address: 'Sidi M\'Hamed, Alger'
  },
  {
    id: 'emp008',
    name: 'Mme. Soraya Mansouri',
    email: 's.mansouri@fsecsg.dz',
    type: 'administratif',
    grade: 'Secrétaire Principal',
    currentEchelon: 4,
    appointmentDate: new Date('2019-05-15'),
    lastEvaluationScore: 15.5,
    status: 'active',
    department: 'Scolarité',
    salary: 62000,
    phoneNumber: '+213 555 890 123',
    address: 'Bachdjarah, Alger'
  },
  {
    id: 'emp009',
    name: 'Dr. Rachid Belhadj',
    email: 'r.belhadj@fsecsg.dz',
    type: 'enseignant',
    grade: 'Maitre Assistant B',
    currentEchelon: 2,
    appointmentDate: new Date('2020-09-10'),
    lastEvaluationScore: 17.5,
    status: 'active',
    department: 'Sciences de Gestion',
    salary: 68000,
    phoneNumber: '+213 555 901 234',
    address: 'Bouzareah, Alger'
  },
  {
    id: 'emp010',
    name: 'M. Omar Zidane',
    email: 'o.zidane@fsecsg.dz',
    type: 'administratif',
    grade: 'Ingénieur d\'Application',
    currentEchelon: 8,
    appointmentDate: new Date('2014-01-08'),
    lastEvaluationScore: 18.2,
    status: 'active',
    department: 'Informatique',
    salary: 85000,
    phoneNumber: '+213 555 012 345',
    address: 'Oued Smar, Alger'
  },
  {
    id: 'emp011',
    name: 'Dr. Nabila Bouchenak',
    email: 'n.bouchenak@fsecsg.dz',
    type: 'enseignant',
    grade: 'Maitre de Conférences A',
    currentEchelon: 5,
    appointmentDate: new Date('2018-03-22'),
    lastEvaluationScore: 19.0,
    status: 'active',
    department: 'Sciences Commerciales',
    salary: 88000,
    phoneNumber: '+213 555 123 456',
    address: 'Cheraga, Alger'
  },
  {
    id: 'emp012',
    name: 'Mme. Aicha Benaissa',
    email: 'a.benaissa@fsecsg.dz',
    type: 'administratif',
    grade: 'Attaché d\'Administration',
    currentEchelon: 3,
    appointmentDate: new Date('2021-06-01'),
    lastEvaluationScore: 14.8,
    status: 'active',
    department: 'Finances',
    salary: 55000,
    phoneNumber: '+213 555 234 567',
    address: 'Dely Brahim, Alger'
  }
];